# Generated by Django 4.0.2 on 2022-03-09 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_topic', to='vote.topic')),
                ('replyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Topic_replyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
