# Generated by Django 4.0.2 on 2022-03-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.topic'),
        ),
    ]
