# Generated by Django 4.0.2 on 2022-03-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lclass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='root',
            field=models.CharField(default='', max_length=100),
        ),
    ]
