# Generated by Django 4.0.2 on 2022-03-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lclass', '0002_job_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ones',
            field=models.TextField(default=''),
        ),
    ]
