# Generated by Django 4.0.2 on 2022-03-09 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lclass', '0004_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='likey',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
